# Generated by Django 6.0.7 on 2026-07-26 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Unique category code. Example: VEG, FRT, RICE.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Category display name.', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for mobile/web.', max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Category hierarchy level.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active.')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this category is visible to customers.')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.category')),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_type', models.CharField(choices=[('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('GRAIN', 'Grain'), ('PULSE', 'Pulse'), ('DAIRY', 'Dairy'), ('FLOWER', 'Flower'), ('HERB', 'Herb'), ('SPICE', 'Spice'), ('OIL_SEED', 'Oil Seed'), ('DRY_FRUIT', 'Dry Fruit'), ('HONEY', 'Honey'), ('EGG', 'Egg'), ('FISH', 'Fish'), ('MEAT', 'Meat'), ('PLANT', 'Plant'), ('OTHER', 'Other')], max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_unit', models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram'), ('QUINTAL', 'Quintal'), ('TON', 'Ton'), ('LITER', 'Liter'), ('ML', 'Milliliter'), ('PIECE', 'Piece'), ('UNIT', 'Unit'), ('DOZEN', 'Dozen'), ('BUNCH', 'Bunch'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('SACK', 'Sack'), ('CRATE', 'Crate')], max_length=20)),
                ('storage_type', models.CharField(choices=[('AMBIENT', 'Ambient'), ('REFRIGERATED', 'Refrigerated'), ('FROZEN', 'Frozen')], default='AMBIENT', max_length=30)),
                ('season', models.CharField(choices=[('YEAR_ROUND', 'Year Round'), ('SUMMER', 'Summer'), ('WINTER', 'Winter'), ('MONSOON', 'Monsoon'), ('SEASONAL', 'Seasonal')], default='YEAR_ROUND', max_length=30)),
                ('shelf_life_days', models.PositiveIntegerField(default=0)),
                ('is_perishable', models.BooleanField(default=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='product_cat_code_fe6111_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='product_cat_name_d66187_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='product_cat_slug_801f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='product_cat_parent__fb81c8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='product_cat_is_acti_f5a665_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_visible'], name='product_cat_is_visi_98c831_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='product_cat_is_feat_9321a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_per_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='products_product_15b636_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_product_af48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_is_feat_19b203_idx'),
        ),
    ]
