# Generated by Django 6.0.7 on 2026-07-26 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmer_other_farming_type_alter_farmer_farming_type'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listing_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(default=1)),
                ('pickup_available', models.BooleanField(default=False)),
                ('home_delivery', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_certified', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional information from the supplier.')),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LIVE', 'Live'), ('OUT_OF_STOCK', 'Out of Stock'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='farmers.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='products.product')),
            ],
            options={
                'db_table': 'supplier_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_code'], name='supplier_pr_listing_4d5c43_idx'), models.Index(fields=['farmer'], name='supplier_pr_farmer__74495b_idx'), models.Index(fields=['product'], name='supplier_pr_product_236e22_idx'), models.Index(fields=['status'], name='supplier_pr_status_96b612_idx'), models.Index(fields=['selling_price'], name='supplier_pr_selling_ba6b93_idx'), models.Index(fields=['is_organic'], name='supplier_pr_is_orga_fc4e08_idx'), models.Index(fields=['is_visible'], name='supplier_pr_is_visi_67acf3_idx'), models.Index(fields=['is_featured'], name='supplier_pr_is_feat_98efa2_idx')],
                'constraints': [models.UniqueConstraint(fields=('farmer', 'product'), name='unique_farmer_product')],
            },
        ),
    ]
