# Generated by Django 6.0.7 on 2026-07-25 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('farmer_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('farming_type', models.CharField(choices=[('CROPS', 'Crops'), ('DAIRY', 'Dairy'), ('POULTRY', 'Poultry'), ('FISHERIES', 'Fisheries'), ('MIXED', 'Mixed Farming')], max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(default='Telugu', max_length=50)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15)),
                ('preferred_payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farmers',
                'ordering': ['farmer_code'],
            },
        ),
    ]
