# Generated by Django 6.0.7 on 2026-07-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='other_farming_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farming_type',
            field=models.CharField(choices=[('CROPS', 'Crops'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('ORGANIC', 'Organic Farming'), ('DAIRY', 'Dairy'), ('POULTRY', 'Poultry'), ('FISHERIES', 'Fisheries'), ('HONEY', 'Honey & Beekeeping'), ('FLOWERS', 'Flowers'), ('SPICES', 'Spices'), ('HERBS', 'Herbs'), ('PLANT_NURSERY', 'Plant Nursery'), ('MIXED', 'Mixed Farming'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
