# Generated by Django 6.0.7 on 2026-07-26 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.CharField(choices=[('CATEGORY', 'Category'), ('PRODUCT', 'Product'), ('SUPPLIER', 'Supplier'), ('ORDER', 'Order'), ('PAYMENT', 'Payment')], db_index=True, max_length=30, unique=True)),
                ('prefix', models.CharField(max_length=10)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Business Sequence',
                'verbose_name_plural': 'Business Sequences',
                'db_table': 'business_sequences',
                'ordering': ['entity'],
            },
        ),
    ]
