# Generated by Django 6.0.7 on 2026-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssequence',
            name='entity',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('PRODUCT', 'Product'), ('SUPPLIER', 'Supplier'), ('LISTING', 'Listing'), ('LOCATION', 'Location'), ('ORDER', 'Order'), ('PAYMENT', 'Payment')], db_index=True, max_length=30, unique=True),
        ),
    ]
